language: ruby
os:
- osx
osx_image: xcode8.3
rvm:
- 2.4.1
- 2.3.5
- 2.2.8
- 2.1.10
branches:
  except:
  - gh-pages
  - /\/v\d/
script:
- gem install bundler
- bundle exec rake travis:build
notifications:
  slack:
    secure: Ksji5MDNOWnuzuyu9Hblbxse6kGLdH4kXyYkF98C+wawIGLSONWWkuA65wpdqSLtBN/79RCLMWoBzKAGX4xy9BL6Rxb3rLjAMT+FVur6II2yaApzyJ0dmTVeTXnkchPcrO27FK5taPb0Ghr86DUiG3OViY/q1N0AVALDYce5tfE=
